# Subjects list 
subjects = [
    "Arrays & Strings",
    "Hashmaps & Sets",
    "2 Pointers",
    "Stacks",
    "Linked Lists",
    "Binary Search",
    "Sliding Windows",
    "Trees",
    "Heaps",
    "Recursive Backtracking",
    "Graphs",
    "Dynamic Programming"
    ]

difficulties = ["Easy", "Medium", "Hard"]

# Problem_set ["Subject", "Difficulty", "Title", "Problem link", **"Completed"**]
problem_set = [
    ["Arrays & Strings", "Easy", "Find Closest Number to Zero", "https://leetcode.com/problems/find-closest-number-to-zero/description/"],
    ["Arrays & Strings", "Easy", "Merge Strings Alternately", "https://leetcode.com/problems/merge-strings-alternately/"],
    ["Arrays & Strings", "Easy", "Roman to Integer", "https://leetcode.com/problems/roman-to-integer/"],
    ["Arrays & Strings", "Easy", "Is Subsequence", "https://leetcode.com/problems/is-subsequence/"],
    ["Arrays & Strings", "Easy", "Best Time to Buy and Sell Stock", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"],
    ["Arrays & Strings", "Easy", "Longest Common Prefix", "https://leetcode.com/problems/longest-common-prefix/"],
    ["Arrays & Strings", "Easy", "Summary Ranges", "https://leetcode.com/problems/summary-ranges/"],
    ["Arrays & Strings", "Medium", "Product of Array Except Self", "https://leetcode.com/problems/product-of-array-except-self/"],
    ["Arrays & Strings", "Medium", "Merge Intervals", "https://leetcode.com/problems/merge-intervals/"],
    ["Arrays & Strings", "Medium", "Spiral Matrix", "https://leetcode.com/problems/spiral-matrix/"],
    ["Arrays & Strings", "Medium", "Rotate Image", "https://leetcode.com/problems/rotate-image/"],
    ["Hashmaps & Sets", "Easy", "Jewels and Stones", "https://leetcode.com/problems/jewels-and-stones/"],
    ["Hashmaps & Sets", "Easy", "Contains Duplicate", "https://leetcode.com/problems/contains-duplicate/"],       
    ["Hashmaps & Sets", "Easy", "Ransom Note", "https://leetcode.com/problems/ransom-note/"],
    ["Hashmaps & Sets", "Easy", "Valid Anagram", "https://leetcode.com/problems/valid-anagram/"],
    ["Hashmaps & Sets", "Easy", "Maximum Number of Balloons", "https://leetcode.com/problems/maximum-number-of-balloons/"],
    ["Hashmaps & Sets", "Easy", "Two Sum", "https://leetcode.com/problems/two-sum/"],
    ["Hashmaps & Sets", "Medium", "Valid Sudoku", "https://leetcode.com/problems/valid-sudoku/"],
    ["Hashmaps & Sets", "Medium", "Group Anagrams", "https://leetcode.com/problems/group-anagrams/"],
    ["Hashmaps & Sets", "Easy", "Majority Element", "https://leetcode.com/problems/majority-element/"],
    ["Hashmaps & Sets", "Hard", "Longest Consecutive Sequence", "https://leetcode.com/problems/longest-consecutive-sequence/"],
    ["2 Pointers", "Easy", "Squares of a Sorted Array", "https://leetcode.com/problems/squares-of-a-sorted-array/"],
    ["2 Pointers", "Easy", "Reverse String", "https://leetcode.com/problems/reverse-string/"],
    ["2 Pointers", "Medium", "Two Sum II - Input Array Is Sorted", "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/"],
    ["2 Pointers", "Easy", "Valid Palindrome", "https://leetcode.com/problems/valid-palindrome/"],
    ["2 Pointers", "Medium", "3Sum", "https://leetcode.com/problems/3sum/"],
    ["2 Pointers", "Medium", "Container With Most Water", "https://leetcode.com/problems/container-with-most-water/"],
    ["2 Pointers", "Hard", "Trapping Rain Water", "https://leetcode.com/problems/trapping-rain-water/"],
    ["Stacks", "Easy", "Baseball Game", "https://leetcode.com/problems/baseball-game/"],
    ["Stacks", "Easy", "Valid Parentheses", "https://leetcode.com/problems/valid-parentheses/"],
    ["Stacks", "Medium", "Evaluate Reverse Polish Notation (RPN)", "https://leetcode.com/problems/evaluate-reverse-polish-notation/"],
    ["Stacks", "Medium", "Daily Temperatures", "https://leetcode.com/problems/daily-temperatures/"],
    ["Stacks", "Medium", "Min Stack", "https://leetcode.com/problems/min-stack/"],
    ["Linked Lists", "Easy", "Remove Duplicates from Sorted List", "https://leetcode.com/problems/remove-duplicates-from-sorted-list/"],
    ["Linked Lists", "Easy", "Reverse Linked List", "https://leetcode.com/problems/reverse-linked-list/"],        
    ["Linked Lists", "Easy", "Merge Two Sorted Lists", "https://leetcode.com/problems/merge-two-sorted-lists/"],  
    ["Linked Lists", "Easy", "Linked List Cycle", "https://leetcode.com/problems/linked-list-cycle/"],
    ["Linked Lists", "Easy", "Middle of the Linked List", "https://leetcode.com/problems/middle-of-the-linked-list/"],
    ["Linked Lists", "Medium", "Remove Nth Node from End of List", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/"],
    ["Linked Lists", "Medium", "Copy List with Random Pointer", "https://leetcode.com/problems/copy-list-with-random-pointer/"],
    ["Binary Search", "Easy", "Binary Search", "https://leetcode.com/problems/binary-search/"],
    ["Binary Search", "Easy", "Search Insert Position", "https://leetcode.com/problems/search-insert-position/"],
    ["Binary Search", "Easy", "First Bad Version", "https://leetcode.com/problems/first-bad-version/"],
    ["Binary Search", "Easy", "Valid Perfect Square", "https://leetcode.com/problems/valid-perfect-square/"],
    ["Binary Search", "Medium", "Search a 2D Matrix", "https://leetcode.com/problems/search-a-2d-matrix/"],
    ["Binary Search", "Medium", "Find Minimum in Rotated Sorted Array", "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"],
    ["Binary Search", "Medium", "Search in Rotated Sorted Array", "https://leetcode.com/problems/search-in-rotated-sorted-array/"],
    ["Binary Search", "Medium", "Koko Eating Bananas", "https://leetcode.com/problems/koko-eating-bananas/"],
    ["Sliding Window", "Easy", "Maximum Average Subarray I", "https://leetcode.com/problems/maximum-average-subarray-i/"],
    ["Sliding Window", "Medium", "Max Consecutive Ones III", "https://leetcode.com/problems/max-consecutive-ones-iii/"],
    ["Sliding Window", "Medium", "Longest Substring Without Repeating Characters", "https://leetcode.com/problems/longest-substring-without-repeating-characters/"],
    ["Sliding Window", "Medium", "Longest Repeating Character Replacement", "https://leetcode.com/problems/longest-repeating-character-replacement/"],
    ["Sliding Window", "Medium", "Minimum Size Subarray Sum", "https://leetcode.com/problems/minimum-size-subarray-sum/"],
    ["Sliding Window", "Medium", "Permutation in String", "https://leetcode.com/problems/permutation-in-string/"],
    ["Trees", "Easy", "Invert Binary Tree", "https://leetcode.com/problems/invert-binary-tree/"],
    ["Trees", "Easy", "Maximum Depth of Binary Tree", "https://leetcode.com/problems/maximum-depth-of-binary-tree/"],
    ["Trees", "Easy", "Balanced Binary Tree", "https://leetcode.com/problems/balanced-binary-tree/"],
    ["Trees", "Easy", "Diameter of Binary Tree", "https://leetcode.com/problems/diameter-of-binary-tree/"],
    ["Trees", "Easy", "Same Binary Tree", "https://leetcode.com/problems/same-tree/"],
    ["Trees", "Easy", "Symmetric Tree", "https://leetcode.com/problems/symmetric-tree/"],
    ["Trees", "Easy", "Path Sum", "https://leetcode.com/problems/path-sum/"],
    ["Trees", "Medium", "Subtree of Another Tree", "https://leetcode.com/problems/subtree-of-another-tree/"],
    ["Trees", "Medium", "Binary Tree Level Order Traversal (BFS)", "https://leetcode.com/problems/binary-tree-level-order-traversal/"],
    ["Trees", "Medium", "Kth Smallest Element in a BST", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/"],
    ["Trees", "Easy", "Minimum Absolute Difference in BST", "https://leetcode.com/problems/minimum-absolute-difference-in-bst/"],
    ["Trees", "Medium", "Validate Binary Search Tree", "https://leetcode.com/problems/validate-binary-search-tree/"],
    ["Trees", "Medium", "Lowest Common Ancestor of a Binary Search Tree", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/"],
    ["Trees", "Medium", "Implement Trie (Prefix Tree)", "https://leetcode.com/problems/implement-trie-prefix-tree/"],
    ["Heaps", "Easy", "Last Stone Weight", "https://leetcode.com/problems/last-stone-weight/"],
    ["Heaps", "Medium", "Kth Largest Element in an Array", "https://leetcode.com/problems/kth-largest-element-in-an-array/"],
    ["Heaps", "Medium", "Top K Frequent Elements", "https://leetcode.com/problems/top-k-frequent-elements/"],
    ["Heaps", "Medium", "K Closest Points to Origin", "https://leetcode.com/problems/k-closest-points-to-origin/"],
    ["Heaps", "Hard", "Merge K Sorted Linked Lists", "https://leetcode.com/problems/merge-k-sorted-lists/"],
    ["Recursive Backtracking", "Medium", "Subsets", "https://leetcode.com/problems/subsets/"],
    ["Recursive Backtracking", "Medium", "Permutations", "https://leetcode.com/problems/permutations/"],
    ["Recursive Backtracking", "Medium", "Combinations", "https://leetcode.com/problems/combinations/"],
    ["Recursive Backtracking", "Medium", "Combination Sum", "https://leetcode.com/problems/combination-sum/"],    
    ["Recursive Backtracking", "Medium", "Letter Combinations of a Phone Number", "https://leetcode.com/problems/letter-combinations-of-a-phone-number/"],
    ["Recursive Backtracking", "Medium", "Generate Parentheses", "https://leetcode.com/problems/generate-parentheses/"],
    ["Recursive Backtracking", "Medium", "Word Search", "https://leetcode.com/problems/word-search/"],
    ["Graphs", "Easy", "Find if Path Exists in Graph", "https://leetcode.com/problems/find-if-path-exists-in-graph/"],
    ["Graphs", "Medium", "Number of Islands", "https://leetcode.com/problems/number-of-islands/"],
    ["Graphs", "Medium", "Max Area of Island", "https://leetcode.com/problems/max-area-of-island/"],
    ["Graphs", "Medium", "Course Schedule (Detecting Cycles in a Graph)", "https://leetcode.com/problems/course-schedule/"],
    ["Graphs", "Medium", "Course Schedule II (Topological Sort)", "https://leetcode.com/problems/course-schedule-ii/"],
    ["Graphs", "Medium", "Pacific Atlantic Water Flow", "https://leetcode.com/problems/pacific-atlantic-water-flow/"],
    ["Graphs", "Medium", "Clone Graph", "https://leetcode.com/problems/clone-graph/"],
    ["Graphs", "Medium", "Rotting Oranges", "https://leetcode.com/problems/rotting-oranges/"],
    ["Graphs", "Medium", "Min Cost to Connect All Points (Prim's Algorithm to Create MST)", "https://leetcode.com/problems/min-cost-to-connect-all-points/"],
    ["Graphs", "Medium", "Network Delay Time (Dijkstra's Algorithm)", "https://leetcode.com/problems/network-delay-time/"],
    ["Dynamic Programming", "Easy", "Fibonacci Number", "https://leetcode.com/problems/fibonacci-number/"],       
    ["Dynamic Programming", "Easy", "Climbing Stairs", "https://leetcode.com/problems/climbing-stairs/"],
    ["Dynamic Programming", "Easy", "Min Cost Climbing Stairs", "https://leetcode.com/problems/min-cost-climbing-stairs/"],
    ["Dynamic Programming", "Medium", "House Robber", "https://leetcode.com/problems/house-robber/"],
    ["Dynamic Programming", "Medium", "Unique Paths", "https://leetcode.com/problems/unique-paths/"],
    ["Dynamic Programming", "Medium", "Maximum Subarray (Kadane's Algorithm)", "https://leetcode.com/problems/maximum-subarray/"],
    ["Dynamic Programming", "Medium", "Jump Game", "https://leetcode.com/problems/jump-game/"],
    ["Dynamic Programming", "Medium", "Coin Change", "https://leetcode.com/problems/coin-change/"],
    ["Dynamic Programming", "Medium", "Longest Increasing Subsequence", "https://leetcode.com/problems/longest-increasing-subsequence/"],
    ["Dynamic Programming", "Medium", "Longest Common Subsequence", "https://leetcode.com/problems/longest-common-subsequence/"],
]
